### ISSUE TITLE
How to create model instances which are many-to-many

### ISSUE THREAD

**Issue by DanCardin** [dgilland/sqlservice#2]
In the docs it says `model.update` works for 1:1 and 1:m, but is there a nice way to ensure the mapping table rows are inserted in a m:m relation?

Right now, I just created an association model and set up the relation so it points to the mapping table. Something along the lines of 
```python
class Parent(models.Model):
    __tablename__ = 'parent'

    id = Column(types.Integer(), primary_key=True, autoincrement=True)

    children = orm.relation('Association')


class Association(models.Model):
    __tablename__ = 'association'
    parent_id = Column(types.Integer(), ForeignKey('parent.id'), primary_key=True)
    child_id = Column(types.Integer(), ForeignKey('child.id'), primary_key=True)

    children = orm.relation('Child')
```
and
```python
parent = models.Parent(dict(
    children=[{'child_id': _id} for _id in ids],
))
```

but it would be nice to be able to ignore the existence (for the most part) of the mapping table like normal.

**Comment by dgilland** [comment]
Is something like this what you are thinking of:

```python
class Parent(Model):
    __tablename__ = 'parent'
    id = Column(types.Integer(), primary_key=True, autoincrement=True)
    children = orm.relation('Association')

class Child(Model):
    __tablename__ = 'child'
    id = Column(types.Integer(), primary_key=True, autoincrement=True)

class Association(Model):
    __tablename__ = 'association'
    parent_id = Column(types.Integer(), ForeignKey('parent.id'), primary_key=True)
    child_id = Column(types.Integer(), ForeignKey('child.id'), primary_key=True)
    child = orm.relation('Child')

parent = Parent(children=[{'child': {'id': _id}} for _id in range(1, 5)])
db.save(parent)
```

which roughly results in the following SQL (using sqlite):

```sql
INSERT INTO parent DEFAULT VALUES
()
INSERT INTO child (id) VALUES (?)
((1,), (2,), (3,), (4,))
INSERT INTO association (parent_id, child_id) VALUES (?, ?)
((1, 1), (1, 2), (1, 3), (1, 4))
COMMIT
```

That would cover the case where you're just creating new children. It will fail if you need to associate existing children or remove/add children from a parent _unless_ you have modified the relationships to be something like:

```python
class Parent(Model):
    ...
    children = orm.relation('Association', cascade='all, delete-orphan')

class Association(Model):
    ...
    child = orm.relation('Child', cascade='all')
```

However, this will result in `Child` records being deleted if they are removed from a parent (which may be undesirable).

A safer approach if `Child` records can live on their own independent of their parent(s) would be to fetch the `Child` model instances from the database and use those in place of `children=[{'child': child1}, {'child': child2}]` (i.e. where `child1 = db.query(Child).get(1) or Child(id=1)` or something similar). There may be some other edge cases depending on your relationship schema/logic you are modeling.

Given that there are many different ways that M:M relationships can be structured, sqlservice only tries to create new instances of models for relationships when mapping `dict` values given to `Model.update()`. So it's entirely possible to pass nested relationship attributes to `update()` but it's up to the user to implement logic for properly handling relationship mappings if they are more complicated than anything beyond "always create a new model instance for relationships when raw dict values used".

BTW, the implementation for this can be found in [Model.__set_relationship_field](https://github.com/dgilland/sqlservice/blob/6a789bf7aa8b1295ca318b05ee531805dfa21b81/sqlservice/model.py#L96) and more specifically [here](https://github.com/dgilland/sqlservice/blob/6a789bf7aa8b1295ca318b05ee531805dfa21b81/sqlservice/model.py#L112). That part is where a new relationship model instance is created which won't be associated with any record in the database (an alternative here might be to attempt to look up an existing record using the primary key value of the new relationship instance but that is beyond what sqlservice would try to do).

Does all this address your original question or have I gone in the wrong direction? Is there a different approach/enhancement to sqlservice that might better meet your use-case?

**Comment by DanCardin** [comment]
So I'm currently doing something like what your example does (except I'm just trying to create the nested mapping rows, not `Child` rows because my `Child` rows already exist), but otherwise the same. Though I don't have the cascade on the Association table.

I *think* that you're saying its beyond scope to enable something like (with the above example)
```python
children = db.query(Child).find(some_filter)
parent = Parent(children=children)
...
db.query(Parent).get(1).children[0] == # child object rather than the mapping table.
```

I think I'm thinking along the lines of [association object](http://docs.sqlalchemy.org/en/latest/orm/basic_relationships.html#association-pattern) and/or [associationproxy](http://docs.sqlalchemy.org/en/latest/orm/extensions/associationproxy.html) which may or may not work, but wont work in `update` (which is basically the code above). Though I was having trouble using the pattern that the sqlalchemy docs use: Parent is a model, Child is a model, association = Table('name', model.metadata, Parent, Child).

**Comment by dgilland** [comment]
Using SQLAlchemy association is one way to achieve what you want. You can define those like:

```python
class Parent(Model):
    ...
    children = orm.relation('Child', secondary=Association.__table__)

# OR

class Parent(Model):
    ...
    _children = orm.relation('Association')
    children = association_proxy('_children', 'child')
```

If you want more control over getters/setters/expression, you can use [hybrd_property](http://docs.sqlalchemy.org/en/latest/orm/extensions/hybrid.html):

```python
class Parent(Model):
    ...
    _children = orm.relation('Association')

    @hybrid_property
    def children(self):
        return self._children

    @children.setter
    def children(self, values):
        self._children = [Association(child=value) for value in values]

    @children.expression
    def children(self):
        return Child
```

**Comment by DanCardin** [comment]
aha! That works for me! Thanks!
