### ISSUE TITLE
Expose ModelMeta

### ISSUE THREAD

**Issue by adm271828** [dgilland/sqlservice#28]
Hi Derrick,

`as_declarative()` takes a `metaclass` argument whose default is `ModelMeta`. However, `ModelMeta` is not importable from `sqlservice`. This prevent us to write something like:
```python
class MyMeta(ModelMeta):
  ...
    
@as_declarative(..., metaclass = MyMeta)
class MyModel(ModelBase):
  ...
```

I could write:
```python
import sqlservice.model
class MyMeta(sqlservice.model.ModelMeta):
  ...
````
But wouldn't it be better to expose `ModelMeta`? as it seems to me your wrote somewhere in the documentation that anything not imported directly from `sqlservice` is considered private interface and subject to change in the future.

Regards, 

Antoine

**Comment by dgilland** [comment]
Seems reasonable. I'll include it in the next release which should be coming out some time soon.

In the meantime, you can just import it with `from sqlservice.model import ModelMeta`.

**Comment by dgilland** [comment]
`from sqlservice import ModelMeta` now works in sqlservice 2.0: https://pypi.org/project/sqlservice/2.0.0/

However, sqlservice 2.0 is a large rewrite with many backwards incompatibilities to conform to the SQLAlchemy 2.0 style of doing things. Be prepared if planning to upgrade. There is a migration guide in the docs to help, though.
