### ISSUE TITLE
type annotations

### ISSUE THREAD

**Issue by tabebqena** [dgilland/sqlservice#31]
Looks awesome !!

Is there is a plan to add type annotations for this project?

**Comment by dgilland** [comment]
Yes, type annotations are planned for v2 which is currently in the works.

**Comment by tabebqena** [comment]
Thanks for your response

**Comment by dgilland** [comment]
sqlservice 2.0 has been release: https://pypi.org/project/sqlservice/2.0.0/

It includes type annotations but the release is a large rewrite to prepare for the SQLAlchemy 2.0 way of doing things. There is a sqlservice 2.0 migration guide in the docs to help.
