### ISSUE TITLE
BUG: query.save 

### ISSUE THREAD

**Issue by tabebqena** [dgilland/sqlservice#35]
From the example in the documentations:

     data = {'name': 'Jenny', 'email': 'jenny@example.com', 'phone': '555-867-5309'}
     user = db.User.save(data)

But I got:
     
        u.save(data)
       File "/mnt/nvme0n1p7/Others/Programming/PROGRAMMING/flask_apps/lamma/.venv/lib/python3.8/site-packages/sqlservice/query.py", line 165, in save
     models = model_class(data)
     TypeError: __init__() takes 1 positional argument but 2 were given

After debugging, The line 165 in query.py

       if is_sequence(data):
            models = (
                model_class(item) if not isinstance(item, model_class) else item
                for item in data
            )
        elif not isinstance(data, model_class):
            models = model_class(data)   # <<<<<<
        else:
            models = data
   
If changed to:

    models = model_class(**data)

It works as expected. But I didn't try other `data` types (tuples, lists, etc) or run tests. 

    

If it changed to :
         
# Edit:
when i tried another data types like list/tuple of dicts, I got error  in anothe line of the same method:

    if is_sequence(data):
            models = (
                model_class(item) # <<<<<<<<<<<
                if not isinstance(item, model_class)
                else item
                for item in data
            )

The fix similar to the previous one:

     if is_sequence(data):
            models = (
                model_class(**item)
                if not isinstance(item, model_class)
                else item
                for item in data
            )

**Comment by dgilland** [comment]
Given this error: `TypeError: __init__() takes 1 positional argument but 2 were given`

Did you by chance modify the model's `__init__()` method?

The default `ModelBase.__init__()` method takes 2 positional arguments: `self` and `_data`

https://github.com/dgilland/sqlservice/blob/369dfa5d1f95aae7129ff793006d70ce666d0dbc/src/sqlservice/model.py#L44-L45

The `db.SomeModel.save(data)` use-case is covered by unit tests like this:

https://github.com/dgilland/sqlservice/blob/369dfa5d1f95aae7129ff793006d70ce666d0dbc/tests/test_query.py#L324-L331

But if I override the `ModelBase.__init__()` method and change its signature to something like:

```python
class ModelBase:
    def __init__(self, **kwargs):
        self.update(**kwargs)
```

then I can reproduce your error:

```python
tests/test_query.py::test_insert_model[AModel-data_pool0] FAILED                                                                                                                                                                                                                                 [ 16%]

=============================================================================================================================================== FAILURES ===============================================================================================================================================
_________________________________________________________________________________________________________________________________ test_insert_model[AModel-data_pool0] _________________________________________________________________________________________________________________________________

db = <SQLClient('sqlite://')>, model_query = <sqlservice.query.SQLQuery object at 0x107cfce80>, data_pool = {<class 'tests.fixtures.AModel'>: {'name': 'dcqDojOm', 'text': 'kkWxnlMZ'}, <class 'tests.fixtures.BModel'>: {'name': 'dGIamSUP'}}

    def test_insert_model(db, model_query, data_pool):
        """Test query model insert."""
        data = data_pool[model_query.model_class]
>       model = model_query.save(data)

tests/test_query.py:327: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sqlservice.query.SQLQuery object at 0x107cfce80>, data = {'name': 'dcqDojOm', 'text': 'kkWxnlMZ'}, before = None, after = None, identity = None

    def save(self, data, before=None, after=None, identity=None):
        """
        Save `data` into the database using insert, update, or upsert-on-primary-key.
    
        Warning:
            This requires that the ``Query`` has been generated using ``Query(<ModelClass>)``;
            otherwise, and exception will be raised.
    
        The `data` argument can be any of the following:
    
        - ``dict``
        - :attr:`model_class` instance
        - ``list``/``tuple`` of ``dict`` objects
        - ``list``/``tuple`` of :attr:`model_class` instances
    
        This method will attempt to do the "right" thing by mapping any items in `data` that have
        their primary key set with the corresponding record in the database if it exists.
    
        Args:
            data (mixed): Data to save to database.
            before (function, optional): Function to call before each model is saved via
                ``session.add``. Function should have signature ``before(model, is_new)``.
            after (function, optional): Function to call after each model is saved via
                ``session.add``. Function should have signature ``after(model, is_new)``.
            identity (function, optional): Function used to return an idenity map for a given model.
                Function should have the signature ``identity(model)``. Defaults to
                :func:`.core.primary_identity_map`.
    
        Returns:
            :attr:`model_class`: If a single item passed in.
            list: A ``list`` of :attr:`model_class` when multiple items passed.
    
        Raises:
            InvalidRequestError: When :attr:`model_class` is ``None``.
        """
        model_class = self._only_model_class_zero("save")
    
        if is_sequence(data):
            models = (
                model_class(item) if not isinstance(item, model_class) else item for item in data
            )
        elif not isinstance(data, model_class):
>           models = model_class(data)
E           TypeError: __init__() takes 1 positional argument but 2 were given

src/sqlservice/query.py:160: TypeError
```

**Comment by tabebqena** [comment]
This is an excellent debugging.

This is my complete code:
     


     from sqlalchemy import Column, Integer, String
     from sqlalchemy import Column
     from sqlservice import SQLClient, declarative_base
     from sqlalchemy.ext.declarative import declarative_base   # << This is the cause , when I removed this line, all things ran Ok.
     
     Base = declarative_base()


    class User(Base):
        __tablename__ = "users"
        id = Column(Integer(), primary_key=True)
        name = Column(String(100))
        email = Column(String(100))
        phone = Column(String(10))


    if __name__ == "__main__":
        client = SQLClient(model_class=Base, database_uri="sqlite:///datax.sqlite3")
        client.create_all()
        data = {
            "name": "Jenny",
            "email": "jenny@example.com",
            "phone": "555-867-5309",
        }

        client.User.save(data)

**Comment by tabebqena** [comment]
Thanks for your excellent reply.

    from sqlalchemy import Column, Integer, String
    from sqlalchemy import Column
    from sqlservice import SQLClient, declarative_base
    from sqlalchemy.ext.declarative import (
        declarative_base,
    )  # << This is the cause , when I removed this line, all things ran Ok.

    Base = declarative_base()


    class User(Base):
        __tablename__ = "users"
        id = Column(Integer(), primary_key=True)
        name = Column(String(100))
        email = Column(String(100))
        phone = Column(String(10))


    if __name__ == "__main__":
        client = SQLClient(model_class=Base, database_uri="sqlite:///datax.sqlite3")
        client.create_all()
        data = {
            "name": "Jenny",
            "email": "jenny@example.com",
            "phone": "555-867-5309",
        }

        client.User.save(data)

**Comment by dgilland** [comment]
Makes sense. The `__init__()` method that `sqlalchemy.ext.declarative.declarative_base` only supports keyword arguments.
