### ISSUE TITLE
Why the `Query` class removed?

### ISSUE THREAD

**Issue by tabebqena** [dgilland/sqlservice#37]
The query class was helpful & provides shorthand for many functionalities.

As the migration guide of `Sqlalchemy 2.0`:

     The biggest visible change in SQLAlchemy 2.0 is the use of [Session.execute()] in conjunction 
     with [select()] to run ORM queries, instead of using [Session.query()]. 
     As mentioned elsewhere, there is no plan to actually remove the [Session.query()] API itself, 
     as it is now implemented by using the new API internally it will remain as a legacy API, and both APIs can 
     be used freely.

I suggest to leave the `Query` class as a legacy API

**Comment by dgilland** [comment]
Feel free to borrow what you need from the sqlservice v1 SQLQuery class for your needs. You can set the query class for the session via the `session_options` argument to the `Database` like `Database(session_options={'query_cls': SQLQuery})`.

I removed the SQLQuery class in favor of only supporting a single API for query execution. Having multiple ways of executing queries could be confusing so I only wanted to support one way, and that way was the new SQLAlchemy 2.0 style.

**Comment by tabebqena** [comment]
Thanks for reply.

I had already upgraded to `sqlservice 2.0.0` & I will adapt to the new changes. 
My suggestion come because there is features that I missed after upgrade.

In the previous version, `sqlservice.SQLClient` was a common entry point that handles all database related actions.  it was the `fascade` of `sqlalchemy` **The missed sqlalchemy API**

I was able to do: 
    
    client.session
    client.add
    client.add_all
    client.save
    client.delete
    # etc ... other session related methods 
    
    client.query(User).save
    client.query(User).find
    client.query(User).find_one
    client.query(User).find_all
    client.query(User).search    # << Was very helpful 
    client.query(User).paginate  # << Was very helpful
    # etc 

    client.User.     # equals to client.query(User)

I know that I can do reach the same functionality in the recent version. but the previous API was more simpler.

Thanks for your effort.
