### ISSUE TITLE
Multiple databases support

### ISSUE THREAD

**Issue by tabebqena** [dgilland/sqlservice#38]
Hello, 

Is there is ability to support multiple database per session, that is discussed [here](https://docs.sqlalchemy.org/en/14/orm/persistence_techniques.html#session-partitioning)

    engine1 = create_engine('postgresql://db1')
    engine2 = create_engine('postgresql://db2')

    Session = sessionmaker()

    # bind User operations to engine 1, Account operations to engine 2
    Session.configure(binds={User:engine1, Account:engine2})

    session = Session()

I can't figure out how to pass options to achieve this behavior.

**Comment by dgilland** [comment]
There's nothing built into sqlservice that does this but seems like one possible solution could be to create a new Database-like class that accepts multiple Database instances along with the session binds and then configures its own session per the method described.

**Comment by tabebqena** [comment]
Can't  subclass the  ``Database``  class ?
