### ISSUE TITLE
unique() call needed in save_all method?

### ISSUE THREAD

**Issue by adm271828** [dgilland/sqlservice#41]
Hello,

I'have been using `sqlservice` with SQLAlchemy1.4 and now I am migrating over SQLAlchemy 2.0

I trigger an error I absolutely do not understand... but it seems a single modification on `sqlservice` source code resolves it easily. Of course I don't know if this is a correct fix or if my code is buggy. Help and/or explanations are welcome!

The error is shown below.

```shell
Traceback (most recent call last):
  File "...\src\grd\messages\parsers\base.py", line 97, in import_archive
    self.import_file(backend, istream, ctx, depth = depth + 1, **kwargs)
  File "...\src\grd\messages\parsers\base.py", line 142, in import_file
    method(backend, path_or_stream, context, **kwargs)
  File "...\src\grd\messages\parsers\f03.py", line 896, in import_file_f03_ax
    session.save_all(parts)
  File "C:\Users\Home\.virtualenvs\sfe-dev-3.12\Lib\site-packages\sqlservice\session.py", line 254, in save_all
    existing_models_by_pk = {model_pk(model): model for model in results}
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Home\.virtualenvs\sfe-dev-3.12\Lib\site-packages\sqlalchemy\engine\result.py", line 519, in iterrows
    hashed = strategy(obj) if strategy else obj
             ^^^^^^^^^^^^^
  File "C:\Users\Home\.virtualenvs\sfe-dev-3.12\Lib\site-packages\sqlalchemy\orm\loading.py", line 283, in require_unique
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: The unique() method must be invoked on this Result, as it contains results that include joined eager loads against collections
```

And the fix is here: in the `session.py` file of `sqlservice`, add a `unique()` call as suggested by error message above.

```python
    def save_all(self, models: t.Union[t.Iterable[t.Any], t.Any]) -> t.List[t.Any]:

        [... skip code ...]

        for model_group, select_models_stmt in iter_mergeable_models_by_class(models):
            results = self.execute(select_models_stmt).scalars().unique()  # <--- MODIFICATION
            existing_models_by_pk = {model_pk(model): model for model in results}
```

The model for wich I use `save_all()` holds a list of other models, that are created within the same session. Error seems be be related to those items.

```python
class InvoicePart(ManagedBase):
  ...

  items: Mapped[List['InvoiceItem']] = relationship(
    back_populates = 'part', 
    lazy = 'joined', 
    cascade = 'all, delete-orphan'
  )

class InvoiceItem(ModelBase):

  # Keys
  _uid: Mapped[int] = mapped_column(primary_key = True)
  _part_id: Mapped[int] = mapped_column(ForeignKey('grd_invoice_part._uid'))

  ...

  # Relationships
  part: Mapped['InvoicePart'] = relationship(back_populates = 'items')
```

In the creation scenario, I create many parts, each of them having many items, within a session and use a 'save_all()' over the parts at the end.

Best regards, 

Antoine

**Comment by adm271828** [comment]
Hi Derrick,

thanks. 

You are right: this is probably also related to my model. I will try to isolate a simple test case in order to understand where it comes from. I'm not quite sure this is the right fix, because, with the `unique()` call added it seems it triggers other errors in parts of the code where it didn't without the call.

What puzzles me is that I basically translated the models from SQLA 1.4 into SQLA 2.0 and the model creation follows the same logic as before.

Don't release it before I find some time to investigate a little bit more...

Best regards,

Antoine

**Comment by dgilland** [comment]
Just to be clear, are you saying that the fix resolved the `sqlalchemy.exc.InvalidRequestError` exception you originally saw, but now there is some other exception happening elsewhere on your end? Or are there now new errors happening within sqlservice?

**Comment by adm271828** [comment]
> Just to be clear, are you saying that the fix resolved the `sqlalchemy.exc.InvalidRequestError` exception you originally saw, but now there is some other exception happening elsewhere on your end? Or are there now new errors happening within sqlservice?

Within sqlservice, at the very same location...

**Comment by adm271828** [comment]
Hi Derrick,

I finished the transition to SQLA 2.0, by rewriting all my models with the new syntax and without any change into structure and relationships. I didn't change the way my models were created either.

I confirm the problem I had is fixed by https://github.com/dgilland/sqlservice/commit/fe73d73a33a9f1024b63afe0ecc85b1a429fb410.

Best regards,

Antoine

**Comment by dgilland** [comment]
I release v3.0.0 which contains this fix: https://pypi.org/project/sqlservice/3.0.0/
